// Get Products
export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";
export const RECEIVE_SELECTEDPRODUCTS = "RECEIVE_SELECTEDPRODUCTS";
export const FETCH_SELECTEDPRODUCTS_BEGIN = "FETCH_SELECTEDPRODUCTS_BEGIN";
export const FETCH_SINGLE_SELECTEDPRODUCT = "FETCH_SINGLE_SELECTEDPRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const POST_REVIEW_DONE = "POST_REVIEW_DONE";
export const RECEIVE_REVIEWS = "RECEIVE_REVIEWS";
export const FETCHED_REVIEW_DONE = "FETCHED_REVIEW_DONE";
// Woocomerce user

export const FETCH_USERWOO_BEGIN = "FETCH_USERWOO_BEGIN";
export const RECEIVE_USERWOO = "RECEIVE_USERWOO";
export const FETCH_USERWOO = "FETCH_USERWOO";

// User
export const FETCH_LOGIN_BEGIN = "FETCH_LOGIN_BEGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const FETCH_LOGIN = "FETCH_LOGIN";
export const LOGOUT = "FETCH_LOGOUT";
export const DESTROY_SESSION = "DESTROY_SESSION";
export const SIGNUP_BEGIN = "SIGNUP_BEGIN";
export const SIGNUP_ = "SIGNUP";
export const RECEIVE_SIGNUP = "RECEIVE_SIGNUP";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const RECEIVE_UPDATED_ACCOUNT = "RECEIVE_UPDATED_ACCOUNT";

// Order
export const ORDER_BEGIN = "ORDER_BEGIN";
export const PLACE_ORDER = "PLACE_ORDER";
export const RECEIVE_ORDER_RECEIPT = "RECEIVE_ORDER_RECEIPT";

// Get CategoryTree
export const FETCH_CATEGORYTREE_BEGIN = "FETCH_CATEGORYTREE_BEGIN";
export const RECEIVE_CATEGORYTREE = "RECEIVE_CATEGORYTREE";
export const FETCH_CATEGORYTREE = "FETCH_CATEGORYTREE";

// Get Extras
export const RECEIVE_EXTRAS = "RECEIVE_EXTRAS";
export const FETCH_EXTRAS_BEGIN = "FETCH_EXTRAS_BEGIN";

// FILTERS
export const FILTER_BRAND = "FILTER_BRAND";
export const FILTER_COLOR = "FILTER_COLOR";
export const FILTER_PRICE = "FILTER_PRICE";
export const SORT_BY = "SORT_BY";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";

// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_QTY = "INCREMENT_QTY";
export const DECREMENT_QTY = "DECREMENT_QTY";
export const CLEAR_CART = "CLEAR_CART";

// WishList
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const CLEAR_WISHLIST = "CLEAR_WISHLIST";

// Compare
export const ADD_TO_COMPARE = "ADD_TO_COMPARE";
export const REMOVE_FROM_COMPARE = "REMOVE_FROM_COMPARE";
export const CLEAR_COMPARE = "CLEAR_COMPARE";

// CheckOut Process
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";

// Newsletter Subscription

export const SUBSCRIPTION_DONE = "SUBSCRIPTION_DONE";
